version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      timezone: UTC
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
