task:
  name: Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  release_script:
    - chmod +x "$PWD/bin/7z"
    - brew install 7zip
    - mkdir -p "$HOME/bin"
    - curl https://rtx.pub/rtx-latest-macos-arm64 > "$HOME/bin/rtx"
    - chmod +x "$HOME/bin/rtx"
    - echo "PATH=$HOME/bin:$PATH" >> $CIRRUS_ENV
    - echo "RTX_TRUSTED_CONFIG_PATHS="$PWD/.rtx.toml"
    - echo "RTX_YES="yes"
    - export PATH=$HOME/bin:$PATH
    - rtx install
    - for path in $(rtx bin-paths); do export PATH="$path:$PATH"; done
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - chmod +x priv/cmd
    - PATH="$PWD/bin:$PATH" MIX_ENV=prod mix release
  binary_artifacts:
    path: burrito_out/*
