name: Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: elixir-tools/private-workflows/.github/workflows/release.yaml@main
    with:
      repo: elixir-tools/next-ls
      tag: ${{ github.event.release.tag_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
