name: Lint Commit
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: commitlint

    steps:
      - uses: actions/checkout@v4
      - name: Install Deps
        run: yarn install
      - name: Lint PR Title
        run: echo "${{ github.event.pull_request.title }}" | yarn commitlint
